server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #动态路由要加的，开启动态路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址(静态路由)
          uri: lb://cloud-payment-service #(动态路由要加的) 匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #匹配后提供服务的路由地址
            - After=2021-04-13T14:02:21.936+08:00[Australia/Perth] #要在这个时间以后才能访问

        - id: payment_routh2 #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001 #匹配后提供服务的路由地址（静态路由）
          uri: lb://cloud-payment-service #（动态路由要加的）lb:loadbalanced
          predicates:
            - Path=/payment/lb/** #匹配后提供服务的路由地址

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka